//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugasAkhir.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web;

    public partial class claim_medical
    {
        public int id_claim { get; set; }
        public string nama_pasien { get; set; }
        public string hubungan { get; set; }
        public string tipe_perawatan { get; set; }
        public Nullable<System.DateTime> tanggal_perawatan { get; set; }
        public string nama_dokter { get; set; }
        public string lokasi_RS { get; set; }
        public string no_telp { get; set; }
        public string diagnosa { get; set; }
        public string status { get; set; }
        public int total_tagihan { get; set; }
        public int nik { get; set; }
        public int total_claim { get; set; }
        public string file_kwintasi { get; set; }
        [NotMapped]
        public HttpPostedFileBase filekwintasi { get; set; }
        public System.DateTime tanggal { get; set; }
        public string keterangan { get; set; }
        public string oleh { get; set; }

        public virtual saldo_medical saldo_medical { get; set; }
    }
}
