//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugasAkhir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuti_massal
    {
        public int id_massal { get; set; }
        public System.DateTime tanggal { get; set; }
        public string keterangan { get; set; }
        public string oleh { get; set; }
    }
}
