//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugasAkhir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuti_user
    {
        public int nik { get; set; }
        public int jatah_cuti { get; set; }
        public int sisa_cuti { get; set; }
        public System.DateTime valid_jatah { get; set; }
        public System.DateTime valid_sisa { get; set; }
    
        public virtual user user { get; set; }
    }
}
