//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugasAkhir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_surat
    {
        public int id_surat { get; set; }
        public string nama_bank { get; set; }
        public string keperluan { get; set; }
        public string no_passport { get; set; }
        public Nullable<System.DateTime> tgl_pergi { get; set; }
        public Nullable<System.DateTime> tgl_pulang { get; set; }
        public string tujuan { get; set; }
        public string tujuan_instansi { get; set; }
        public string kegiatan { get; set; }
        public string lokasi { get; set; }
    
        public virtual surat surat { get; set; }
    }
}
