//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugasAkhir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saldo_awal
    {
        public int id_saldo { get; set; }
        public int default_inap { get; set; }
        public int default_jalan { get; set; }
        public int default_kacamata { get; set; }
    }
}
