//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugasAkhir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saldo_medical
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public saldo_medical()
        {
            this.claim_medical = new HashSet<claim_medical>();
        }
    
        public int nik { get; set; }
        public int saldo_rawatinap { get; set; }
        public int saldo_rawatjalan { get; set; }
        public int saldo_kacamata { get; set; }
        public System.DateTime valid_rawat { get; set; }
        public System.DateTime valid_kacamata { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<claim_medical> claim_medical { get; set; }
        public virtual user user { get; set; }
    }
}
