//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugasAkhir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class surat
    {
        public int id_surat { get; set; }
        public int id_jenis { get; set; }
        public Nullable<int> nik { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public string status { get; set; }
        public string keterangan { get; set; }
        public string oleh { get; set; }
    
        public virtual detail_surat detail_surat { get; set; }
        public virtual jenis_surat jenis_surat { get; set; }
        public virtual user user { get; set; }
    }
}
